title: An Introduction to Solving Biological Problems with R
description: based on the University of Cambridge R Course
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
