title: An Introduction to Solving Biological Problems with R
description: PMacDaSci Intro to R course *(based on the Cambridge Basic R Course)*
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
